name: Informační architektura
description: Projekt do předmětu NAMI na KISK FF MU
paginate: 10
#gems: [jekyll-paginate]

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

google_analytics: UA-77448292-1

